### ISSUE TITLE
QueryFile

### ISSUE THREAD

**Issue by vitaly-t** [singular000/node-express-pgp-many-to-many#1]
the information here is false: https://github.com/singular000/node-express-pgp-many-to-many/blob/ff3f896d2e13aadaa882541c067804188b9a3f31/README.md#dev-notes

see option `debug` in QueryFile options: http://vitaly-t.github.io/pg-promise/QueryFile.html#.Options

**Comment by tpage000** [comment]
Thank you, please let me know if you see other weirdness
